### ISSUE TITLE
Actions ignored during charging session

### ISSUE THREAD

**Issue by VLWilliam** [dannerph/homeassistant-keba#34] opened 2024-11-22 09:47 UTC
Hi

I would like to balance the electrical consumption by regulating the charging power while charging the car. However, I'm facing some issues:

When no car is connected to the charging station, the 'set current' action functions correctly. The charging station adopts the set current, and if I set a delay time, I can see (in my case) the entity "sensor.keba_p30_time_until_planned_current_is_set" counting down. Once the delay time elapses, "sensor.keba_p30_set_current" adopts the preset current, which seems to be working correctly.

However, as soon as a car starts charging, the previously set current reverts back to its maximum value. After this, it is no longer possible to reduce the current. If I attempt to use the set current action (which uses the underlying UDP command currtime), the delay timer counts down for a few seconds, but before the timer reaches 0s the current is reset already back to its maximum value and the timer stops counting. I don't think it's only this action that has an issue but something more in general, because the start and stop commands also seem to be either ignored or overridden during a charging session. If I try to stop the session, charging stops for approximately 2 seconds and then resumes.

This issue occurs with various car brands, so it doesn't seem to be caused by a specific car. And I already tried with 'failsafe mode' on and off, no difference.

* Using custom_component version 3.0.3 in Home Assistant version 2024.11.1.
* Charging station: Keba P30, firmware version 3.10.53, with SolarEdge branding.

Does anyone have tips on how I can better troubleshoot where the resetting/overwriting during charging comes from, or has anyone experienced similar problems and already found an explanation or solution for this?

Thank you in advance!

**Comment by pos-ei-don** [comment] 2024-11-22 09:50
It works perfectly for me.

**Comment by dannerph** [comment] 2024-12-22 19:18
@VLWilliam If it working if you send the udp commands directly during a charging process? I would try to find out if it is caused by the charging station or by the home assistant integration

**Comment by dannerph** [comment] 2024-12-23 17:55
@VLWilliam Another idea: some charging stations have a swtich as input to authorize the charging process. If you say, even when you stop it, it restarts again, maybe the switch input is activated all the time?

**Comment by lorenzolaiti** [comment] 2024-12-24 15:09
Hello, same problem here. Until a few days ago, everything was working fine, but now during charging, I can't change the amperage or stop the charging process. Actually, the commands are successful, but after a few seconds, they are overridden by something. Here are the log lines:
2024-12-24 14:38:21,671 DEBUG - LogEvt: Event time: [2024-12-24 14:38:21,652] [24828377] timed ENA condition met: 13000

2024-12-24 14:38:25,282 DEBUG - LogEvt: Event time: [2024-12-24 14:38:25,263] [24828377] timed ENA condition met: 25000
I'm going crazy!

**Comment by lorenzolaiti** [comment] 2024-12-26 21:52
@VLWilliam Is the Keba charging station connected to a solar management system? If so, what brand do you have? I'm trying to understand if the issue might be coming from that. I tried sniffing the UDP commands between the charging station and Home Assistant, but I didn’t find anything unusual. I also tried turning off Home Assistant and sending the UDP commands manually, but it behaved the same way.

**Comment by lorenzolaiti** [comment] 2024-12-28 08:19
@VLWilliam The common points are the integration for reading data from the inverter and the brand of the inverter (even though I have a different model, but still SolarEdge). I tried turning off Home Assistant and sending UDP commands directly, and the behavior is the same, so I would rule out an issue with the integrations.
The things that could be done are:
	•	Update the charging station. I see that mine is version .14, while the latest release is .18. Are you also on this version?
	•	Try disconnecting the OCPP connection with SolarEdge.

Have you already tried either of these two attempts?

**Comment by dannerph** [comment] 2024-12-28 20:49
Ok, it seems that some external source is changing the state of your charging station. That is nothing I can fix in the integration of Home Assistant. I will close this issue now.

**Closed by dannerph** 2024-12-28 20:49 UTC
