### ISSUE TITLE
Cannot start/stop station trough service keba.enable / disable

### ISSUE THREAD

**Issue by mzsergiu** [dannerph/homeassistant-keba#1] opened 2022-01-15 12:29 UTC
I created a button on dashboard. Configured Tap Action -> "Call Service" -> Service: Keba Charging Station : Enable (keba.enable), then Wallbox - ticked the box and selected Device is KEBA P30. 

I get message: 

Failed to call service keba/enable. Enable parameter must be True or False.

If I un-tick the Wallbox. I dont get the error, but nothing happens.

With original Keba component from core, it worked also if I send trough UDP ena 1/0 station responds correctly. My Keba P30 does not support authentification, it`s the KEBA KeContact P30 Germany edition DE 440 AC wallbox

![image](https://user-images.githubusercontent.com/8598216/149621774-5a9c69c6-c1b0-4640-a47a-e8ceb98ebccb.png)

**Comment by dannerph** [comment] 2022-01-16 14:29
Thanks for reporting! The issue is fixed in the latest release.

**Closed by dannerph** 2022-01-16 14:29 UTC
